### ISSUE TITLE
Unhandled error event.

### ISSUE THREAD

**Issue by mlvo83** [bocoup/j5ik-reconbot-tessel-edition#2]
I have tried everything I can think off. I have no idea how to get this last part of the project to work. Do you have any idea how to fix this issue.

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn /tmp/remote-script/video.sh ENOENT
    at exports._errnoException (util.js:907:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickDomainCallback (node.js:397:17)

**Comment by rwaldron** [comment]
Here's a run through, from beginning to end: 

```
rwaldron in ~/clonez
$ git clone git@github.com:bocoup/j5ik-reconbot-tessel-edition.git
Cloning into 'j5ik-reconbot-tessel-edition'...
remote: Counting objects: 68, done.
remote: Total 68 (delta 0), reused 0 (delta 0), pack-reused 68
Receiving objects: 100% (68/68), 328.78 KiB | 0 bytes/s, done.
Resolving deltas: 100% (26/26), done.
rwaldron in ~/clonez
$ cd j5ik-reconbot-tessel-edition/
rwaldron in ~/clonez/j5ik-reconbot-tessel-edition on master
$ ls
.
├── [drwxr-xr-x rwaldron staff     408 Nov 14 13:20]  .git/
├── [drwxr-xr-x rwaldron staff     136 Nov 14 13:20]  app/
├── [drwxr-xr-x rwaldron staff     102 Nov 14 13:20]  lib/
├── [-rw-r--r-- rwaldron staff      13 Nov 14 13:20]  .gitignore
├── [-rw-r--r-- rwaldron staff      14 Nov 14 13:20]  .tesselinclude
├── [-rw-r--r-- rwaldron staff    305K Nov 14 13:20]  bots-eye-view.png
├── [-rw-r--r-- rwaldron staff    1.9K Nov 14 13:20]  index.js
├── [-rw-r--r-- rwaldron staff    1009 Nov 14 13:20]  install.js
├── [-rw-r--r-- rwaldron staff     969 Nov 14 13:20]  motors.js
├── [-rw-r--r-- rwaldron staff     349 Nov 14 13:20]  package.json
├── [-rw-r--r-- rwaldron staff      23 Nov 14 13:20]  readme.md
└── [-rwxr-xr-x rwaldron staff     122 Nov 14 13:20]  video.sh*

3 directories, 9 files
rwaldron in ~/clonez/j5ik-reconbot-tessel-edition on master
$ t2 list
INFO Searching for nearby Tessels...
  LAN ash
  USB ash
rwaldron in ~/clonez/j5ik-reconbot-tessel-edition on master
$ npm install
npm WARN package.json j5ik-reconbot-tessel-edition@0.0.1 No repository field.
\
> serialport@4.0.6 install /Users/rwaldron/clonez/j5ik-reconbot-tessel-edition/node_modules/johnny-five/node_modules/serialport
> node-pre-gyp install --fallback-to-build

[serialport] Success: "/Users/rwaldron/clonez/j5ik-reconbot-tessel-edition/node_modules/johnny-five/node_modules/serialport/build/Release/serialport.node" is installed via remote
tessel-io@0.7.2 node_modules/tessel-io

express@4.14.0 node_modules/express
├── escape-html@1.0.3
├── content-type@1.0.2
├── methods@1.1.2
├── vary@1.1.0
├── parseurl@1.3.1
├── etag@1.7.0
├── array-flatten@1.1.1
├── utils-merge@1.0.0
├── cookie-signature@1.0.6
├── merge-descriptors@1.0.1
├── encodeurl@1.0.1
├── content-disposition@0.5.1
├── fresh@0.3.0
├── path-to-regexp@0.1.7
├── cookie@0.3.1
├── range-parser@1.2.0
├── serve-static@1.11.1
├── depd@1.1.0
├── qs@6.2.0
├── on-finished@2.3.0 (ee-first@1.1.1)
├── debug@2.2.0 (ms@0.7.1)
├── finalhandler@0.5.0 (unpipe@1.0.0, statuses@1.3.1)
├── proxy-addr@1.1.2 (forwarded@0.1.0, ipaddr.js@1.1.1)
├── type-is@1.6.13 (media-typer@0.3.0, mime-types@2.1.12)
├── accepts@1.3.3 (negotiator@0.6.1, mime-types@2.1.12)
└── send@0.14.1 (destroy@1.0.4, ms@0.7.1, statuses@1.3.1, mime@1.3.4, http-errors@1.5.0)

socket.io@1.5.1 node_modules/socket.io
├── has-binary@0.1.7 (isarray@0.0.1)
├── socket.io-parser@2.3.1 (isarray@0.0.1, json3@3.3.2, component-emitter@1.1.2)
├── debug@2.2.0 (ms@0.7.1)
├── socket.io-adapter@0.4.0 (socket.io-parser@2.2.2)
├── engine.io@1.7.2 (base64id@0.1.0, accepts@1.3.3, ws@1.1.1, engine.io-parser@1.3.1)
└── socket.io-client@1.5.1 (to-array@0.1.4, component-emitter@1.2.0, indexof@0.0.1, object-component@0.0.3, component-bind@1.0.0, backo2@1.0.2, parseuri@0.0.4, engine.io-client@1.7.2)

johnny-five@0.10.5 node_modules/johnny-five
├── lodash.debounce@4.0.8
├── lodash.clonedeep@4.5.0
├── ease-component@1.0.0
├── browser-serialport@2.0.3
├── color-convert@1.2.2
├── temporal@0.5.0
├── nanotimer@0.3.10
├── firmata@0.14.1
├── chalk@1.1.3 (ansi-styles@2.2.1, supports-color@2.0.0, escape-string-regexp@1.0.5, strip-ansi@3.0.1, has-ansi@2.0.0)
├── es6-shim@0.35.1
└── serialport@4.0.6 (bindings@1.2.1, debug@2.3.2, commander@2.9.0, lie@3.1.0, nan@2.4.0, object.assign@4.0.4)
rwaldron in ~/clonez/j5ik-reconbot-tessel-edition on master
$ t2 run index.js
INFO Looking for your Tessel...
INFO Connected to ash.
INFO Building project.
INFO Writing project to RAM on ash (2007.552 kB)...
INFO Deployed.
INFO Running index.js...
1479147825497 Device(s) Tessel 2 (ash)
1479147825708 Connected Tessel 2 (ash)
Reconbot(T2): Initialized
http://ash.local
http://10.31.0.102
Reconbot(T2): Controller Connected
```

And I snapped this screenshot on my desktop: 

![](https://i.gyazo.com/8410b6523a87223a8edbc911028bce42.png)

Are you running the project from a clone or copy (ie. zip file) of the repository?

**Comment by mlvo83** [comment]
Yes , I'm running the project from a clone of the repo. I literally did  

> git clone https://github.com/bocoup/j5ik-reconbot-tessel-edition.git;

just like you did above, and than I started to run my project from there. Are you on a windows 10 machine. Is there anyway to start over, I have done it on two different machines now. Perhaps third time is a charm. or can i reset my tessel, perhaps I have something wrong? ... though I'm doubtful.

**Comment by rwaldron** [comment]
I will try the whole thing from a Windows 10 machine. Will post back when I know more

**Comment by rwaldron** [comment]
I don't understand why, but when attempted to deploy from windows, the file is sent, but for some reason cannot be found. Regardless, I was able to fix the issue by eliminating the video.sh file entirely. I deployed successfully from my Windows 10 machine. I will push changes shortly

**Comment by rwaldron** [comment]
https://github.com/bocoup/j5ik-reconbot-tessel-edition/commit/325143037893a05fa0002b887c0ec6742c206654

**Comment by mlvo83** [comment]
Awesome! it makes me feel a little better that I'm not just a complete douche. I pull the project again. Really appreciated. I will also add a link to this conversation over on Tessel Support.
